
const app_base_url = "http://localhost:8000/api/v1";

export const url = {
  auth: {
    login: `${app_base_url}/auth/login`,
    logout: `${app_base_url}/auth/logout`,
    register: `${app_base_url}/auth/register`,
    admin: {
      approveUser: (userId: string) => `${app_base_url}/auth/admin/approve-user/${userId}`,
      pendingUsers: `${app_base_url}/auth/admin/pending-users`,
      rejectUser: (userId: string) => `${app_base_url}/auth/admin/reject-user/${userId}`,
    },
  },
  badge: {
    index: `${app_base_url}/badge`,
    store: `${app_base_url}/badge`,
    show: (badgeId: string) => `${app_base_url}/badge/${badgeId}`,
    update: (badgeId: string) => `${app_base_url}/badge/${badgeId}`,
    destroy: (badgeId: string) => `${app_base_url}/badge/${badgeId}`,
  },
  book: {
    index: `${app_base_url}/book`,
    store: `${app_base_url}/book`,
    search: `${app_base_url}/book/search`,
    show: (bookId: string) => `${app_base_url}/book/${bookId}`,
    update: (bookId: string) => `${app_base_url}/book/${bookId}`,
    destroy: (bookId: string) => `${app_base_url}/book/${bookId}`,
    searchGoogle: `${app_base_url}/book/search/google`,
    createFromGoogle: `${app_base_url}/book/google`,
  },
   challenge: {
    index: `${app_base_url}/challenges`,
    store: `${app_base_url}/challenges`,
    show: (challengeId: string) => `${app_base_url}/challenges/${challengeId}`,
    update: (challengeId: string) => `${app_base_url}/challenges/${challengeId}`,
    destroy: (challengeId: string) => `${app_base_url}/challenges/${challengeId}`,
    join: (challengeId: string) => `${app_base_url}/challenges/${challengeId}/join`,
    addBook: (challengeId: string) => `${app_base_url}/challenges/${challengeId}/add-book`,
    updateBook: (recordId: string) => `${app_base_url}/challenges/books/${recordId}`,
    progress: (challengeId: string) => `${app_base_url}/challenges/${challengeId}/progress`,
    leaderboard: (challengeId: string) => `${app_base_url}/challenges/${challengeId}/leaderboard`,
  },
  event: {
    index: `${app_base_url}/events`,
    store: `${app_base_url}/events`,
    show: (eventId: string) => `${app_base_url}/events/${eventId}`,
    update: (eventId: string) => `${app_base_url}/events/${eventId}`,
    destroy: (eventId: string) => `${app_base_url}/events/${eventId}`,
  },
 forum: {
    index: `${app_base_url}/forums`,
    store: `${app_base_url}/forums`,
    show: (forumId: string) => `${app_base_url}/forums/${forumId}`,
    update: (forumId: string) => `${app_base_url}/forums/${forumId}`,
    destroy: (forumId: string) => `${app_base_url}/forums/${forumId}`,
    togglePublic: (forumId: string) => `${app_base_url}/forums/${forumId}/toggle-public`,
    threads: {
      index: (forumId: string) => `${app_base_url}/forums/${forumId}/threads`,
      store: (forumId: string) => `${app_base_url}/forums/${forumId}/threads`,
      togglePin: (forumId: string, threadId: string) => `${app_base_url}/forums/${forumId}/threads/${threadId}/toggle-pin`,
      toggleLock: (forumId: string, threadId: string) => `${app_base_url}/forums/${forumId}/threads/${threadId}/toggle-lock`,
      show: ( threadId: string) => `${app_base_url}/threads/${threadId}`,
      posts: (threadId: string) => `${app_base_url}/threads/${threadId}/posts`,
      
    },
  },
  mention: {
    index: `${app_base_url}/mention`,
    store: `${app_base_url}/mention`,
    show: (mentionId: string) => `${app_base_url}/mention/${mentionId}`,
    update: (mentionId: string) => `${app_base_url}/mention/${mentionId}`,
    destroy: (mentionId: string) => `${app_base_url}/mention/${mentionId}`,
  },
  notification: {
    index: `${app_base_url}/notification`,
    store: `${app_base_url}/notification`,
    show: (notificationId: string) => `${app_base_url}/notification/${notificationId}`,
    update: (notificationId: string) => `${app_base_url}/notification/${notificationId}`,
    destroy: (notificationId: string) => `${app_base_url}/notification/${notificationId}`,
  },
  post: {
    index: `${app_base_url}/post`,
    store: `${app_base_url}/post`,
    show: (postId: string) => `${app_base_url}/post/${postId}`,
    update: (postId: string) => `${app_base_url}/post/${postId}`,
    destroy: (postId: string) => `${app_base_url}/post/${postId}`,
  },
  profile: {
    show: `${app_base_url}/profile`,
    update: `${app_base_url}/profile`,
    destroy: `${app_base_url}/profile`,
  },
  user: {
    index: `${app_base_url}/user`,
    store: `${app_base_url}/user`,
    show: (userId: string) => `${app_base_url}/user/${userId}`,
    update: (userId: string) => `${app_base_url}/user/${userId}`,
    destroy: (userId: string) => `${app_base_url}/user/${userId}`,
    ban: (userId: string) => `${app_base_url}/user/${userId}/ban`,
    
  },
  posts: {  
    update: (postId: string) => `${app_base_url}/posts/${postId}`,
    destroy: (postId: string) => `${app_base_url}/posts/${postId}`,
    like: (postId: string) => `${app_base_url}/posts/${postId}/like`,
    save: (postId: string) => `${app_base_url}/posts/${postId}/save`,
    comment: (postId: string) => `${app_base_url}/posts/${postId}/comment`,
    flag: (postId: string) => `${app_base_url}/posts/${postId}/flag`,
    uploadMedia: (postId: string) => `${app_base_url}/posts/${postId}/media`,
  },
  sanctum: {
    csrfCookie: `${app_base_url}/../sanctum/csrf-cookie`,
  },
  test: `${app_base_url}/test`,
};